import { getAll, getOne } from "../db.js";
import { applyManualStockEntry } from "../stockSync.js";
import { el, inr, toast, todayStr, fmtDate, openModal, closeModal, loadingRow, emptyRow, debounce } from "../utils.js";

let allEntries = [];
let categoryFilter = "all";
let searchTerm = "";
let page = 1;
const PAGE_SIZE = 15;

const CAT_LABEL = { A: "Brand Stock", B: "Customer Sale/Return", C: "Inter-store Transfer", O: "Opening Stock" };

export async function render(root) {
  root.appendChild(el("div", { class: "section-title" }, "Stock In / Out"));

  const summaryGrid = el("div", { class: "kpi-grid", style: "grid-template-columns:repeat(2,1fr)" }, [
    kpiPlaceholder("Total Qty"), kpiPlaceholder("Total Value"),
  ]);
  root.appendChild(summaryGrid);

  const toolbar = el("div", { class: "toolbar" }, [
    el("input", { class: "search", placeholder: "Search remarks or store…", oninput: debounce((e) => { searchTerm = e.target.value.toLowerCase(); page = 1; renderTable(); }, 250) }),
    el("select", { onchange: (e) => { categoryFilter = e.target.value; page = 1; renderTable(); } }, [
      el("option", { value: "all" }, "All categories"),
      el("option", { value: "A" }, "A — Brand Stock"),
      el("option", { value: "B" }, "B — Customer Sale/Return"),
      el("option", { value: "C" }, "C — Inter-store Transfer"),
      el("option", { value: "O" }, "O — Opening Stock"),
    ]),
    el("div", { class: "spacer" }),
    el("button", { class: "btn btn-primary", onclick: () => openCategoryPicker() }, "＋ Add Stock Entry"),
  ]);
  root.appendChild(toolbar);

  const stockTbody = el("tbody", { id: "stock-tbody" });
  stockTbody.innerHTML = loadingRow(6);
  root.appendChild(el("div", { class: "table-wrap" }, el("table", {}, [
    el("thead", {}, el("tr", {}, ["Date", "Category", "In", "Out", "Balance Qty", "Remarks"].map((h) => el("th", {}, h)))),
    stockTbody,
  ])));
  const paginationEl = el("div", { class: "pagination" });
  root.appendChild(paginationEl);

  const [entries, counter] = await Promise.all([
    getAll("stockEntries", { orderBy: ["date", "desc"] }),
    getOne("settings", "stockCounter"),
  ]);
  allEntries = entries;

  summaryGrid.innerHTML = "";
  summaryGrid.appendChild(kpiFilled("Total Qty", (counter?.qty || 0).toLocaleString("en-IN"), "Running balance"));
  summaryGrid.appendChild(kpiFilled("Total Value", inr(counter?.value || 0), "Category A, C & Opening Stock"));

  renderTable();

  function renderTable() {
    const tbody = root.querySelector("#stock-tbody");
    let rows = allEntries.filter((s) => {
      if (categoryFilter !== "all" && s.category !== categoryFilter) return false;
      if (searchTerm && !(s.remarks || "").toLowerCase().includes(searchTerm) && !(s.storeName || "").toLowerCase().includes(searchTerm)) return false;
      return true;
    });
    const totalPages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE));
    page = Math.min(page, totalPages);
    const pageRows = rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

    if (!pageRows.length) { tbody.innerHTML = emptyRow(6, "No stock movements match."); }
    else {
      tbody.innerHTML = "";
      pageRows.forEach((s) => {
        tbody.appendChild(el("tr", {}, [
          el("td", {}, fmtDate(s.date)),
          el("td", {}, el("span", { class: `badge badge-cat${s.category}` }, `${s.category} · ${CAT_LABEL[s.category] || ""}${s.storeName ? " (" + s.storeName + ")" : ""}`)),
          el("td", { class: "num" }, s.stockIn ? el("span", { class: "badge badge-in" }, `+${s.stockIn}`) : "—"),
          el("td", { class: "num" }, s.stockOut ? el("span", { class: "badge badge-out" }, `-${s.stockOut}`) : "—"),
          el("td", { class: "num" }, String(s.cumulativeQty ?? "—")),
          el("td", {}, s.remarks || (s.autoGenerated ? "Auto — from Daily Sales" : "—")),
        ]));
      });
    }
    paginationEl.innerHTML = "";
    paginationEl.appendChild(el("button", { disabled: page <= 1 ? "disabled" : undefined, onclick: () => { page--; renderTable(); } }, "‹ Prev"));
    paginationEl.appendChild(el("span", {}, `Page ${page} of ${totalPages}`));
    paginationEl.appendChild(el("button", { disabled: page >= totalPages ? "disabled" : undefined, onclick: () => { page++; renderTable(); } }, "Next ›"));
  }

  function openCategoryPicker() {
    const body = el("div", { style: "display:flex;flex-direction:column;gap:10px" }, [
      catOption("O", "Opening Stock", "Set your starting stock qty & value — typically used once when you begin using this app, or to correct the baseline."),
      catOption("A", "Brand Stock", "Stock received from or returned to the brand."),
      catOption("C", "Inter-store Transfer", "Stock sent to or received from another Maybell store."),
      el("p", { class: "help-text" }, "Category B (Customer Sale/Return) is generated automatically from Daily Sales entries and can't be added manually here."),
    ]);
    openModal("Add Stock Entry — Choose Category", body);

    function catOption(cat, title, desc) {
      const card = el("div", { class: "card card-pad", style: "cursor:pointer" }, [
        el("strong", {}, `${cat} — ${title}`),
        el("div", { class: "help-text" }, desc),
      ]);
      card.addEventListener("click", () => { closeModal(); openManualEntryModal(cat); });
      return card;
    }
  }

  function openManualEntryModal(category) {
    const date = el("input", { type: "date", value: todayStr() });
    const direction = el("select", {}, [el("option", { value: "in" }, "Stock IN"), el("option", { value: "out" }, "Stock OUT")]);
    const qty = el("input", { type: "number", min: "0", required: "required" });
    const value = el("input", { type: "number", min: "0", step: "0.01" });
    const storeName = el("input", { placeholder: "e.g. Erode Store" });
    const remarks = el("textarea", { rows: "2", placeholder: category === "O" ? "e.g. starting balance as of shop opening" : "e.g. damaged return, rotation to Erode store" });
    const errorMsg = el("p", { class: "login-error" }, "");

    const fields = [
      el("label", { class: "field" }, [el("span", {}, "Date"), date]),
      el("label", { class: "field" }, [el("span", {}, "Direction"), direction]),
      el("label", { class: "field" }, [el("span", {}, "Quantity"), qty]),
      el("label", { class: "field" }, [el("span", {}, category === "O" ? "Total Value (₹) of this stock" : "Value (₹, optional)"), value]),
    ];
    if (category === "C") fields.push(el("label", { class: "field full" }, [el("span", {}, "Store Name / Location"), storeName]));
    fields.push(el("label", { class: "field full" }, [el("span", {}, "Remarks"), remarks]));
    fields.push(errorMsg);

    const form = el("form", { class: "form-grid" }, [
      ...fields,
      el("div", { class: "modal-actions full" }, [
        el("button", { type: "button", class: "btn btn-ghost", onclick: closeModal }, "Cancel"),
        el("button", { type: "submit", class: "btn btn-primary" }, "Add Entry"),
      ]),
    ]);

    form.addEventListener("submit", async (e) => {
      e.preventDefault();
      if (!date.value || !qty.value || Number(qty.value) <= 0) {
        errorMsg.textContent = "Enter a date and a quantity greater than zero.";
        return;
      }
      if (category === "C" && !storeName.value.trim()) {
        errorMsg.textContent = "Store Name / Location is required for inter-store transfers.";
        return;
      }
      const submitBtn = form.querySelector('button[type="submit"]');
      submitBtn.disabled = true;
      submitBtn.textContent = "Saving…";
      try {
        const result = await applyManualStockEntry({
          date: date.value, category,
          stockIn: direction.value === "in" ? qty.value : 0,
          stockOut: direction.value === "out" ? qty.value : 0,
          value: value.value, storeName: storeName.value.trim(), remarks: remarks.value.trim(),
        });
        allEntries.unshift({
          id: result.id, date: date.value, category,
          stockIn: direction.value === "in" ? Number(qty.value) : 0,
          stockOut: direction.value === "out" ? Number(qty.value) : 0,
          cumulativeQty: result.qty, storeName: storeName.value.trim(), remarks: remarks.value.trim(),
        });
        renderTable();
        summaryGrid.innerHTML = "";
        summaryGrid.appendChild(kpiFilled("Total Qty", result.qty.toLocaleString("en-IN"), "Running balance"));
        summaryGrid.appendChild(kpiFilled("Total Value", inr(result.value), "Category A, C & Opening Stock"));
        closeModal();
        toast("Stock entry added", "success");
      } catch (err) {
        console.error(err);
        errorMsg.textContent = "Could not save. Check your connection and try again.";
      } finally {
        submitBtn.disabled = false;
        submitBtn.textContent = "Add Entry";
      }
    });

    openModal(`Add Stock Entry — ${CAT_LABEL[category]}`, form, { wide: true });
  }
}

function kpiPlaceholder(label) {
  return el("div", { class: "kpi-card" }, [el("div", { class: "kpi-label" }, "Loading…"), el("div", {}, label)]);
}
function kpiFilled(label, value, sub) {
  return el("div", { class: "kpi-card" }, [
    el("div", { class: "kpi-label" }, label),
    el("div", { class: "kpi-value" }, value),
    el("div", { class: "kpi-sub" }, sub),
  ]);
}
